# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Betar Blog 
email: team@betar.io 
description: > # this means to ignore newlines until "baseurl:"
  Betar Team Blog, where we are sharing platform updates, new games, team updates and more about Betar and beta testing
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.betar.io" # the base hostname & protocol for your site
twitter_username: Betar_io
github_username: betarteam 

# Build settings
markdown: kramdown
